site_name: Dev Guide
site_description: 'Development guides for CogniPilot'
site_author: 'CogniPilot Foundation'
site_url: 'https://cognipilot.org'

repo_name: 'CogniPilot/cognipilot_docs'
repo_url: 'https://github.com/CogniPilot/cognipilot_docs'

edit_uri: 'edit/main/docs/'

docs_dir: docs/

theme:
  language: en
  name: material
  custom_dir: theme_overrides
  logo: assets/CogniPilotLogoSite.png
  favicon: assets/CogniPilotLogoFavicon.ico
  features:
    - content.code.copy

extra_css:
  - stylesheets/cognipilot-palette.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CogniPilot
    - icon: fontawesome/brands/discord
      link: https://discord.gg/FkDn9cBPuq

copyright: Copyright &copy; 2023 CogniPilot Foundation. All Rights Reserved.

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - macros

nav:
    - Home: index.md
    - Getting Started:
      - Docker Simulation: getting_started/docker_sim.md
    - Cerebri:
      - Zephyr RTOS: cerebri/zephyr/zephyr.md
      - Boards:
        - NXP® RT6: cerebri/boards/nxp_rt6.md
        - POSIX: cerebri/boards/posix.md
      - Platforms:
        - MultiCopters: cerebri/platforms/multicopters.md
        - Rovers: cerebri/platforms/rovers.md
    - Cranium:
      - Corti: cranium/corti/corti.md
      - Oculi: cranium/oculi/oculi.md
      - Pari: cranium/pari/pari.md
      - Tempi: cranium/tempi/tempi.md
      - Synapse: cranium/synapse/synapse.md
      - Compute:
        - NXP® NavQPlus:
          - Setup: cranium/compute/navqplus/setup.md
    - Dream:
      - Launch: dream/launch.md
      - Models: dream/models/models.md
      - Worlds: dream/worlds/worlds.md
    - Electrode:
      - Joystick: electrode/joystick.md
      - RVIZ 2: electrode/rviz2.md
    - Helmet:
      - Install Workspace: helmet/install.md
      - Docker: helmet/docker/docker.md
    - Tools:
      - HCDF: tools/hcdf/hcdf.md
      - Pyecca: tools/pyecca/pyecca.md
    - Spinali:
      - CANFD: spinali/canfd.md
      - Sensors: spinali/sensors/sensors.md
      - Actuators: spinali/actuators/actuators.md
    - Example Systems:
      - MultiCopters:
        - RDDRONE:
          - Hardware: example_systems/rddrone/rddrone.md
          - Simulation: example_systems/rddrone/simulation.md
      - Rovers:
        - Buggy 3:
          - Hardware: example_systems/buggy_3/buggy_3.md
          - Simulation: example_systems/buggy_3/simulation.md
        - El Mandadero:
          - Hardware: example_systems/el_mandadero/el_mandadero.md
          - Simulation: example_systems/el_mandadero/simulation.md
        - MiniMando:
          - Hardware: example_systems/minimando/minimando.md
          - Simulation: example_systems/minimando/simulation.md
    - Resources:
      - Contact: resources/contact.md
      - Contribute: resources/contribute.md
      - CogniPilot Foundation: "https://www.cognipilot.com"
    - Contributors:
      - Companies:
        - NXP: "https://www.nxp.com/"
        - Rudis Laboratories: "https://www.rudislabs.com/"
      - Universities:
        - Purdue: "https://www.purdue.edu/"
