site_name: Release Overview
site_description: 'Development guides for CogniPilot'
site_author: 'CogniPilot Foundation'
site_url: 'https://cognipilot.org'

repo_name: 'CogniPilot/cognipilot_docs'
repo_url: 'https://github.com/CogniPilot/cognipilot_docs'

edit_uri: 'edit/main/docs/'

docs_dir: docs/

theme:
  language: en
  name: material
  custom_dir: theme_overrides
  logo: assets/CogniPilotLogoSite.png
  favicon: assets/CogniPilotLogoFavicon.png
  features:
    - content.code.copy

extra_css:
  - stylesheets/cognipilot-palette.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CogniPilot
    - icon: fontawesome/brands/discord
      link: https://discord.gg/cognipilot

copyright: Copyright &copy; 2023 CogniPilot Foundation. All Rights Reserved.

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - macros

nav:
    - Home: index.md
    - Releases:
      - Airy: "https://airy.cognipilot.org/"
      - B Mythical: releases/b-mythical/index.md
    - Resources:
      - Contribute: resources/contribute.md
      - Hardware:
        - Tropic: resources/hardware/tropic.md
      - CogniPilot Foundation: "https://www.cognipilot.com"
    - Contributors:
      - Companies:
        - NXP: "https://www.nxp.com/"
        - Rudis Laboratories: "https://www.rudislabs.com/"
      - Universities:
        - Purdue: "https://www.purdue.edu/"
